### ISSUE TITLE
Could you please share the train set?

### ISSUE THREAD

**Issue by pierowu** [hkust-zhiyao/RTL-Coder#2]
I'd like to follow this nice work. Could you please share the train set? Thanks.

**Comment by DevinShang** [comment]
Hi, thanks for your interest. We have updated the training dataset "Resyn27k" in the "dataset" file.

**Comment by weidee** [comment]
I am interested in the complete process of Stage 1 , could you provide more info like code or data generated Keyword Pool? thanks.

**Comment by DevinShang** [comment]
Hi, weidee! The most basic data generation code "insruction_gen.py" is provided and you may refer to the paper for details of Stage 1.  Implementing stage 1 requires only a few modifications to the script and the resulting pool contains hundreds of keywords. Hope this helps!

**Comment by pierowu** [comment]
> Hi, thanks for your interest. We have updated the training dataset "Resyn27k" in the "dataset" file.




Thank you for the kind sharing. I've noticed that "Resyn27k" has only one response for each instruction, which is different from 3 code candidates according to the paper. I was wondering if you could make the full data set available?

**Comment by DevinShang** [comment]
@pierowu Hi, pierowu! The objective of scoring training is to make the model generate less low-quality data. Therefore, the code candidates should be generated by your base model or checkpoints at the tunning process. We recommend you generate the code candidates using your base model or checkpoints. Otherwise, the scoring training may even harm your model performance.
